apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000        # service port
      targetPort: 3000  # container port
      nodePort: 31401   # node port
