version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asna@123
    ports:
      - "5432:5432"
    networks:
      - todo-net

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Asna@123
    networks:
      - todo-net

networks:
  todo-net:
